### ISSUE TITLE
Bad performance with multiple video players 

### ISSUE THREAD

**Issue by Burdu** [caprica/vlcj-javafx#11]
Hi,

I am trying to play multiple videos in a JavaFX scene (3 videos to be exact) and the performance is really bad. I didn't see any issue related to multiple video players. Has this been tested before? I get a bad frame rate, most of the times 10-20 FPS.

I did the tests using ResizableJavaFXPlayerTest.java

**Comment by caprica** [comment]
So every frame you are copying something like 1920x1080x4 bytes multiple times, then you multiple by three, and doing all those copies in software... You can work out the bandwidth you need and decide if your PC is fast enough or not...

Or consider rendering to an OGL texture or something.

Direct rendering is not the recommended approach because of precisely the problems you desdribe.

**Comment by Burdu** [comment]
So we can never achieve on JavaFX the same performance we can achieve on Swing?

**Comment by caprica** [comment]
No, in the swing version you have VLC doing native hardware accelerated rendering directly into the component. Even if you used something like OGL it may be better than what you're doing now but never as good as the native performance in a Swing app.

**Comment by Burdu** [comment]
Thanks for your answer. It is really disappointing though, as I can't either add a Swing canvas inside a JavaFX Pane since SwingNode can't handle heavyweight components

**Comment by caprica** [comment]
Find a way to reduce the amount of buffer copies and/or use something like
OGL. That's your solution I'm afraid.

**Comment by caprica** [comment]
Seems to be related: http://stackoverflow.com/questions/34904731/how-to-read-pixel-data-from-a-com-sun-jna-memory-object-efficiently

Interesting suggestion there to try a NIO buffer.

**Comment by Burdu** [comment]
Thanks Mark, I'll look into it
