### ISSUE TITLE
Updating examples

### ISSUE THREAD

**Issue by Linus789** [caprica/vlcj-javafx#17]
Hi,
many examples don't work because of the vlcj update to 4.1.0.
For example the `DirectMediaPlayerComponent` is missing and I have no clue how to replace it.
Therefore I would be grateful if you could update your examples.

Sincerely,
Linus

**Comment by Linus789** [comment]
I managed to update the resizeable example by my own, here it is: https://github.com/caprica/vlcj-javafx/pull/18

Sincerely,
Linus

**Comment by caprica** [comment]
Replacements for obsolete components are described in the vlcj project README.

I had some stalled updates for the JavaFX examples because I was unsure about the best approach for resizing.

The original approach allocated a rendering buffer that was the maximum size of the entire desktop, even if the video was being rendered at 160x80, and downscaled that buffer to what was needed. I'm really not sure that's the right approach.

Now, I prefer to allocate a video buffer of the exact same size as the actual source video, and use the toolkit rendering to scale the video image rather than scaling the video buffer. This is what is done with all of the new vlcj "direct" rendering via the CallbackVideoSurface.

On the other hand I'm keen to reduce as many frame buffer copies as possible.

**Comment by caprica** [comment]
The point is, all of the JavaFX examples are now inherently resizeable, and the example that deals specifically with resizing is probably obsolete.

Anyway, the examples will soon be updated.
