### ISSUE TITLE
Credit and Copyright in Unusual Circumstances

### ISSUE THREAD

**Issue by GeePawHill** [caprica/vlcj-javafx#29]
Folks, this isn't a bug thing, I just wasn't sure quite how to handle the situation.

I work in kotlin on an open-source [project](https://github.com/GeePawHill/kontentment), and I wanted to get away from MediaView in the current app. I liberated this code, and moved it piece-wise into my app. It's not real yet, but the first step, of making sure it works as expected in my wonky openjdk + open javafx + kotlin + tornadofx + gradle build environment is done.

I first just let intellij do the java -> kotlin thing. Now I am transmogrifying it, step-wise again, to fit with general kotlin idiom and my particular style. The resulting files are unlikely to be just a "port", as my needs for my project (and my coding style) are quite different.

I don't want to break license, and I certainly do want to give credit for the excellent work.

How should I handle this?

Cheers,
and thank you very much, it appears to be just what I needed,
GeePaw

**Comment by caprica** [comment]
When you say you "liberated this code, and moved it piece-wise into [your] app", do you mean you liberated *my* code?.

I can't give a legal opinion, but I can give you my personal opinion. You started with my work, then transformed it thereby creating a derivative work, and so consequently that derived work needs to respect the original license (in this case GPL 3.0+).

Having said that...

I care a lot more about vlcj itself than I do this javafx project - so if you tell me that what you're really talking about is that you used code from this vlcj-javafx project as the basis of your own work, well this project is meant to be a demonstration or reference application so I wouldn't be too concerned.

It would be less murky if you just studied this code, then taking what you learnt you implemented what you needed from scratch yourself in Kotlin rather than just transforming my code. 

But like I said above, this is meant to be a reference application showing how to use vlcj with JavaFX, so I don't really see a problem.

IMO you should still give credit, but that's between your and your conscience to decide.

I do appreciate you seeking advice on this, you could have just kept quiet.

If you make a million dollar business on the basis of my code I'd like to receive a small kick-back, so good luck!

If you did the same thing with vlcj itself, I would not be happy at all.

**Comment by GeePawHill** [comment]
Excellent! That's pretty much where I was at.

1) I will _of course_ acknowledge the original in my material, and should I ever make a splash/about etc., I will call it out with links.

2) I am not making a commercial product at all, and do not actually ever want to. I didn't license kontentment yet, but generally in my OSS stuff I use one of the MIT licenses.

3) Though I started by literally copy/pasting files from your hierarchy to mine, the real key is the central idea of using PixelBuffer. 

4) Unlike vlcj, nobody uses my dumb app except me, primarily because it's incredibly painful and awkward to use. Switching away from MediaView (and Animation) as its basis is part of making it theoretically more valuable to humans.

Currently, my build is actually "two headed", with the NanoTimer app and the kontentment app in the same codebase, as that was my prima facie proof that my build could take advantage of your idea. My obvious next step is to make sure I grok your code and integrate the _idea_ in my app rather than the actual transliterated code.

I will keep you apprised as the plot thickens, but even though it's very early days, I didn't want to just ignore the issue.

Thanks!
GeePaw

**Comment by caprica** [comment]
The code showing how to use PixelBuffer was in fact based on a contribution I initially received from a contributor, so I can hardly complain about sharing it.

What you're doing sounds fine to me.

Good luck.
